#
# Splunk app configuration file
#

[install]
is_configured = 0

[ui]
is_visible = true
label = Alex Davison SME Obs

[id]
version = 1.0.5
name = ajdSMEObs1Splunk

[launcher]
author = Alex Davison
description = ajdSMEObs1Splunk
version = 1.0.5

[package]
id = ajdSMEObs1Splunk
check_for_updates = false